name: CI

on:
  workflow_dispatch:

env:
  vcpkg-commit: 90b5fb836cda4eba4569a123bca63b957f55232b
  vcpkg-install: pe-parse uthenticode

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: deps
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format
          sudo pip3 install cmake-format

      - name: format
        run: make format

  winchecksec:
    strategy:
      matrix:
        build-type: ["Release"]
        platform: ["ubuntu-latest"]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - name: Restore from cache and install vcpkg
        uses: lukka/run-vcpkg@v6
        with:
          vcpkgGitCommitId: ${{ env.vcpkg-commit }}
          vcpkgArguments: ${{ env.vcpkg-install }}

      - name: build
        run: |
          mkdir build
          cd build
          cmake \
            -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} \
            -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake \
            -DBUILD_TESTS=0 \
            ..
          cmake --build .

      - name: archive
        run: zip -r build.zip build
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: build.zip

  winchecksec-windows:
    strategy:
      matrix:
        build-arch:
          - { arch: "x64", triplet: "x64-windows" }
        build-type: ["Release"]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Restore from cache and install vcpkg
      uses: lukka/run-vcpkg@v5
      with:
        vcpkgGitCommitId: ${{ env.vcpkg-commit }}
        vcpkgArguments: ${{ env.vcpkg-install }}
        vcpkgTriplet: ${{ matrix.build-arch.triplet }}

    - name: build
      shell: bash
      run: |
        mkdir build
        cd build
        cmake \
          -G "Visual Studio 17 2022" \
          -A ${{ matrix.build-arch.arch }} \
          -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake \
          -DBUILD_TESTS=0 \
          ..
        cmake --build . --config ${{ matrix.build-type }}

    - name: archive
      run:
        7z a build.zip build

    - name: upload
      uses: actions/upload-artifact@v3
      with:
        name: windows-build
        path: build.zip
